version: '3.1'

services:
  loadbalancer:
    image: nginx:1.25
    ports:
      - "80:80"
    networks:
      - common-network
    volumes:
    #  - ./app:/data/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
    - NGINX_PORT=80
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5

  app1:
    image: node:18
    ports:
      - "8080:8080"
    networks:
      - common-network
    volumes:
      - ./app:/home/app
      - ./app/node_modules:/home/app/node_modules
    environment:
      - PORT=8080
    command: node /home/app/index.js

  app2:
    image: node:18
    ports:
      - "8081:8081"
    networks:
      - common-network
    volumes:
      - ./app:/home/app
      - ./app/node_modules:/home/app/node_modules
    environment:
      - PORT=8081
    command: node /home/app/index.js

  app3:
    image: node:18
    ports:
      - "8082:8082"
    networks:
      - common-network
    volumes:
      - ./app:/home/app
      - ./app/node_modules:/home/app/node_modules
    environment:
      - PORT=8082
    command: node /home/app/index.js

  app4:
    image: node:18
    ports:
      - "8083:8083"
    networks:
      - common-network
    volumes:
      - ./app:/home/app
      - ./app/node_modules:/home/app/node_modules
    environment:
      - PORT=8083
    command: node /home/app/index.js

  app5:
    image: node:18
    ports:
      - "8084:8084"
    networks:
      - common-network
    volumes:
      - ./app:/home/app
      - ./app/node_modules:/home/app/node_modules
    environment:
      - PORT=8084
    command: node /home/app/index.js

networks:
  common-network:
    driver: bridge